services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

    db_postgres:
        image: postgres:15
        restart: always
        env_file: .env
        environment:
            POSTGRES_DB: my_database
            POSTGRES_USER: my_pg_user
            POSTGRES_PASSWORD: pg_user
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"