<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250109172208 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add tables for coupon, order, product, and tax entities.';
    }

    public function up(Schema $schema): void
    {
        // Таблица coupon
        $this->addSql('CREATE TABLE coupon (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            "type" VARCHAR(255) NOT NULL, 
            code VARCHAR(10) NOT NULL, 
            discount_amount NUMERIC(10, 2) DEFAULT NULL, 
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            PRIMARY KEY(id)
        )');

        // Таблица order
        $this->addSql('CREATE TABLE "order" (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            amount NUMERIC(10, 2) DEFAULT NULL, 
            status VARCHAR(255) NOT NULL, 
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            PRIMARY KEY(id)
        )');

        // Таблица product
        $this->addSql('CREATE TABLE product (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            name VARCHAR(255) NOT NULL, 
            description TEXT NOT NULL, 
            amount NUMERIC(10, 2) NOT NULL, 
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            PRIMARY KEY(id)
        )');

        // Таблица tax
        $this->addSql('CREATE TABLE tax (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            country_code VARCHAR(2) NOT NULL, 
            percent INT NOT NULL, 
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            PRIMARY KEY(id)
        )');
    }

    public function down(Schema $schema): void
    {
        // Удаление таблиц
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE tax');
    }
}
