services:
 #components
  App\ApiBundle\Components\PaymentProcessor\PaymentProcessor:
    arguments:
      $paymentProviderRegistry: '@App\ApiBundle\Components\PaymentProcessor\PaymentProviderRegistry'

  App\ApiBundle\Components\PaymentProcessor\PaymentProviderRegistry:
    arguments:
      $paymentProviders: !tagged_iterator { tag: 'payment_provider' }

    # Stripe Provider
  App\ApiBundle\Components\PaymentProcessor\Providers\Stripe:
    arguments:
      $paymentProcessor: '@Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor'
    tags:
       - { name: 'payment_provider', key: 'stripe' }

    # PayPal Provider
  App\ApiBundle\Components\PaymentProcessor\Providers\Paypall:
    arguments:
      $paymentProcessor: '@Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor'
    tags:
      - { name: 'payment_provider', key: 'paypal' }

    # Register StripePaymentProcessor as a service
  Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor:
    class: Systemeio\TestForCandidates\PaymentProcessor\StripePaymentProcessor

    # Register PaypalPaymentProcessor as a service
  Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor:
    class: Systemeio\TestForCandidates\PaymentProcessor\PaypalPaymentProcessor
