# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
parameters:

services:
    App\:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/ApiBundle/Components/'
imports:
    - { resource: '../src/ApiBundle/Resources/config/services.yaml' }